/*
 *
 */
package UserUI;

import java.awt.event.KeyEvent;
import java.io.IOException;

/**
 *
 * @author Claudio Caldeirão RA:131255061
 */
public class ProgramUI extends javax.swing.JFrame {
    private float parameter;
    /**
     * Creates new form ProgramUI
     */
    public ProgramUI() {
        initComponents();
    }
    
    public void showMessage(String message) {
        programText.append(message);
    }
    
    public float getParameter() throws IOException {
        programText.append("Insira um valor:");
        return parameter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProgramPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        programText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Program");

        programText.setBackground(new java.awt.Color(0, 0, 0));
        programText.setColumns(20);
        programText.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        programText.setForeground(new java.awt.Color(255, 255, 255));
        programText.setRows(5);
        programText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                programTextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                programTextKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(programText);

        javax.swing.GroupLayout ProgramPanelLayout = new javax.swing.GroupLayout(ProgramPanel);
        ProgramPanel.setLayout(ProgramPanelLayout);
        ProgramPanelLayout.setHorizontalGroup(
            ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgramPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ProgramPanelLayout.setVerticalGroup(
            ProgramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgramPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgramPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void programTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_programTextKeyTyped

    }//GEN-LAST:event_programTextKeyTyped

    private void programTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_programTextKeyPressed
        if((evt.getKeyCode() == KeyEvent.VK_ENTER)) {  
            String text = programText.getText();
            int i = text.lastIndexOf(":");
            parameter = Float.valueOf(text.substring(i + 1));  
            System.out.println(parameter);
        }
    }//GEN-LAST:event_programTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProgramPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea programText;
    // End of variables declaration//GEN-END:variables
}
